### PR TITLE
Update to 0.10.9

### PR DESCRIPTION
**Pull request by TheGiraffe3**
Updates the website to 0.10.9.

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
~~How do you update the submodule `game`? That seems to need to happen as well.~~

EDIT: never mind, I think I've got it.

**Comment by TheGiraffe3** [comment]
@7even is there something wrong with this PR? If so, could you point it out?

**Comment by 7even** [comment]
> @7even is there something wrong with this PR? If so, could you point it out?

I tried to build the site from this branch but it hangs while trying to parse the `remnant outfits.txt` file. Generally this is a common problem after updating the game to a new version - it happens because the parser is somewhat fragile and goes into infinite loop trying to parse something it cannot comprehend (something recently added to the files inside `game/data`).

I'll try to debug the issue.

**Comment by 7even** [comment]
[This](https://github.com/endless-sky/endless-sky/blob/c99fa18cf0c35e2f3c28fc6d418550d6fb8166b3/data/remnant/remnant%20outfits.txt#L408) is the problematic line that cannot be parsed - there is no space between `"hit force"` and `135`. Unfortunately it must be fixed in the game source, I can't make the parser process it (this also means that the parser will be able to process only the game versions after this fix, at least without adding this space manually to `remnant outfits.txt` - and of course all versions before this problem was introduced).

There was another problem with the parser but I was able to fix it in `master`.

**Comment by TheGiraffe3** [comment]
Okay, it's fixed in the game source. Is that all?

**Comment by 7even** [comment]
Well, I prefer to keep the submodule pointing to the latest stable release of the game, so could you please switch it back to `0.10.8`? It will require adding that space manually until the next stable release, but I can do that to release the new version of the website - and to generate it for a newer version, we can always switch the submodule to the game version we need.

**Comment by TheGiraffe3** [comment]
I'm not sure how to do that in this PR, but I'll make another one with that change. Also, the Incipias aren't in 0.10.8, so it's probably better to do it this way.



Does this PR need to be rebased to point to dev.endless-sky.7vn.io?

**Comment by 7even** [comment]
> Does this PR need to be rebased to point to dev.7vn.endless-sky.io?

I'm not sure what you mean. I usually deploy the latest stable release version to `endless-sky.7vn.io` while the latest unstable release goes to `dev.endless-sky.7vn.io` - but right now we can use the latest `master` version of the game as an unstable one.

The problem is, I generated the unstable version and I don't see any Incipias ships in the list (although there are some in the game files). I need to check that later when I have the time.

**Comment by TheGiraffe3** [comment]
I see. I hadn't really known how this worked.
Sounds good!

**Comment by 7even** [comment]
@TheGiraffe3 you can leave this PR as is, I can take it from here when I have the time.

Thank you.

**Comment by TheGiraffe3** [comment]
It doesn't let me update the branch, but I've added the Successors now.

**Comment by TheGiraffe3** [comment]
That wasn't supposed to happen.

**Comment by TheGiraffe3** [comment]
I've got merge conflicts fixed, and 0.10.9 is out in the main game, so I believe this is ready. Everything is updated correctly.
Also, because you do direct merging instead of squashing, I won't inflate the commit count a lot.

**Pull request merged**
